Power safety
iq-motion-control/iq-module-communication-doc pull request #14
Opened 2022-10-05 15:30 UTC by Vertiq-Ben

- Added documentation for power_safety for 2306 speed

2022-10-05 15:37 UTC, iq-fred requested changes

2022-10-05 15:37 UTC, iq-fred commented on docs/clients/power_safety.rst
> +| 3      | volt_input_low        | get, set, save | float     | fix16 | !
Should probably add descriptions to these guys

2022-10-06 22:45 UTC, iq-matt commented on docs/clients/power_safety.rst
> +| 3      | volt_input_low        | get, set, save | float     | fix16 | Minimum threshold value for voltage
Incorrect units.  Match to new python Unit.

2022-10-06 22:45 UTC, iq-matt requested changes
Incorrect units

2022-10-07 14:39 UTC, iq-fred requested changes

2022-10-07 14:39 UTC, iq-fred commented on docs/clients/power_safety.rst
> +The Power Safety protects the motor by checking various parameters in the motor, such as voltage and current, to make sure the values are within a specific range. If the values are above or below the
"lock down" not "locked down". Also, probably worth nothing that it "unlocks" once the parameters are back in the safe region

2022-10-07 18:51 UTC, iq-matt approved these changes

2022-10-07 18:54 UTC, iq-fred approved these changes

2022-10-07 21:56 UTC, merged