Added Angle Control Mechanisms Manual Page
iq-motion-control/iq-module-communication-doc pull request #46
Opened 2023-10-24 12:21 UTC by vertiq-jordan

The text here is essentially identical to that found [here](https://docs.google.com/document/d/1gWE17eilSR97g7EDVOw5WiucLWi_ACHBfN82wD64ZqA/edit) with some grammatical and formatting changes. 

An important note is that in the first paragraph, there is a note to add a link later on. Spoke with Fred, and he wanted this to move forward into PR so that we can get this information out there, even if it's not fully complete. As usual with RTD prs, please check out the actual RTD build.

2023-10-24 12:24 UTC, vertiq-jordan commented on docs/clients/multi_turn_angle_control.rst
> +.. _multi_turn_control_label:
added some references in multi turn that we can use in the angle control manual

2023-10-24 12:25 UTC, vertiq-jordan commented on docs/clients/servo_input_parser.rst
> +.. _servo_input_parser_table:
Just an added reference used in the angle control manual

2023-10-24 12:27 UTC, vertiq-jordan commented on docs/manual/manual_angle_control_mechanisms.rst
> +be found <link to the velocity control page>. TODO: ADD ACTUAL LINK TO VELOCITY CONTROL WHEN IT EXISTS
This is the only link that does not exist yet. Moving forward with the PR to get the information at least onto a findable branch for people who need it.

2023-10-24 15:30 UTC, Vertiq-Ben approved these changes

2023-10-25 17:49 UTC, iq-fred requested changes

2023-10-25 17:49 UTC, iq-fred commented on docs/manual/manual_angle_control_mechanisms.rst
> +then a Control Angle of 25 rad will take about 0.5 seconds.
Probably obvious, but a control angle of 25 radians will take 0.5 seconds assuming you start from 0 displacement. May be good to specify

2023-10-25 17:49 UTC, iq-fred commented on docs/manual/manual_angle_control_mechanisms.rst
> +total distance (radial or linear) traveled away from *Zero Angle*. Displacement is not bounded by [-:math:`\pi`, :math:`\pi`], and can be any 32-bit float
Might want to say "floating point" value instead of "float". Float is just shorthand for that

2023-10-25 17:49 UTC, iq-fred commented on docs/manual/manual_angle_control_mechanisms.rst
> +    #Expect to see a value around PI\
Extra slash at the end of the line here

2023-10-25 18:04 UTC, vertiq-jordan commented on .readthedocs.yaml
> +      python: "3.8"
Yep. Couldn't build without it: https://docs.readthedocs.io/en/stable/config-file/v2.html#build and https://blog.readthedocs.com/use-build-os-config/

2023-10-25 18:06 UTC, vertiq-jordan commented on docs/manual/manual_angle_control_mechanisms.rst
> +radians ctrl_angle or output meters ctrl_linear_displacement (assuming meters_per_radian is non-zero. See :ref:`Angular v. Linear Control`).
Grrr, yea they're supposed to be italicized. Tried to get them all from the document, but must have missed some. The italics formatting doesn't copy/paste :(

2023-10-25 18:13 UTC, vertiq-jordan commented on docs/manual/manual_angle_control_mechanisms.rst
> +This guide will focus on only the Position mode. Other modes are covered more in <info about input parser stuff>.
coming soon. will fix

2023-10-26 17:06 UTC, iq-fred requested changes

2023-10-26 18:12 UTC, iq-fred commented on docs/manual/manual_angle_control_mechanisms.rst
> +As with all trajectories, the position takes a smooth route to its final displacement, and we once again at a final
"and we once again at a final...", seems to be missing a word. Should it be end or end up at ?

2023-10-26 18:16 UTC, iq-fred approved these changes

2023-10-26 19:26 UTC, iq-matt commented on docs/_static/manual_images/angle_control/belt_drive.png
This picture makes sense when the radius of the pulley is 0.5m.

2023-10-26 19:28 UTC, iq-matt commented on docs/_static/manual_images/angle_control/lead_screw_example.png
As drawn, this picture shows 3.5 revolutions = 22 radians.  The label says it's only 1 radian of turning though.  I think this is quite confusing.

2023-10-26 19:33 UTC, iq-matt commented on docs/_static/manual_images/angle_control/linear_displacement.png
As drawn, the output angle is incorrect.  

On the input/module 3.14 rad = 3 teeth-worth of rotation.  This is drawn as 3.14 rad correctly.
On the output the angle should also be 3 teeth-worth of rotation, but it's more like 4.2.

2023-10-26 19:55 UTC, iq-matt commented on docs/manual/manual_angle_control_mechanisms.rst
> +    #Set the control displacement to 0 rad
Set to coast, not 0 rad

2023-10-26 20:03 UTC, iq-matt approved these changes

2023-10-26 20:05 UTC, merged